### ISSUE TITLE
楼主，怎么下载你的项目老是报数据库连接错误呢

### ISSUE THREAD

**Issue by you521** [acumen1005/Recommendation#1]

**Comment by acumen1005** [comment]
什么错误发出来看看。。

**Comment by you521** [comment]
楼主你有其他的联系方式？

**Comment by you521** [comment]
有些问题想请你指导一下

**Comment by acumen1005** [comment]
有问题这里发出来不是很好吗？（企鹅： echo NDA3NjYwMTA5Cg== |base64 --d

**Comment by you521** [comment]
现在一运行项目就报少数据库表，你GitHub上提供的数据库表和程序里用到的完全对不上呀

**Comment by you521** [comment]
少了几个表，楼主能不能分享一下完整的数据库表呢

**Comment by you521** [comment]
？？？？

**Comment by you521** [comment]
楼主在吗？你的demo我还是没有调出来呀

**Comment by murdonson** [comment]
![image](https://user-images.githubusercontent.com/20641803/34339316-a3268030-e9ad-11e7-92cb-6693f8185426.png)
repo主 就这一个功能吗

**Comment by acumen1005** [comment]
目前，只做了这个功能。
